https://gist.github.com/Deryck97/dff8d33e9f841568201a2a0d5519ac5e

In [1]:
import pandas as pd

In [2]:
YEAR = 2021

In [3]:
data = pd.read_csv('https://github.com/nflverse/nflverse-data/releases/download/pbp/' \
                   'play_by_play_' + str(YEAR) + '.csv.gz',
                   compression= 'gzip', low_memory= False)

In [4]:
data

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,NaN,NaN,NaN,...,0,1,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,TEN,home,ARI,...,0,1,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,55,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,TEN,home,ARI,...,0,1,-1.399805,NaN,NaN,NaN,NaN,NaN,0.491433,-49.143299
3,76,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,TEN,home,ARI,...,0,1,0.032412,1.165133,5.803177,4.0,0.896654,0.125098,0.697346,30.265415
4,100,2021_01_ARI_TEN,2021091207,TEN,ARI,REG,1,TEN,home,ARI,...,0,1,-1.532898,0.256036,4.147637,2.0,0.965009,0.965009,0.978253,2.174652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50707,3930,2021_22_LA_CIN,2022021300,CIN,LA,POST,22,CIN,home,LA,...,0,0,-1.215366,NaN,NaN,NaN,NaN,NaN,0.681295,-68.129545
50708,3951,2021_22_LA_CIN,2022021300,CIN,LA,POST,22,NaN,NaN,NaN,...,0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50709,3968,2021_22_LA_CIN,2022021300,CIN,LA,POST,22,CIN,home,LA,...,0,0,-0.623479,0.271249,4.355069,2.0,0.998861,0.998861,0.747601,25.239891
50710,3990,2021_22_LA_CIN,2022021300,CIN,LA,POST,22,LA,away,CIN,...,0,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50711,4011,2021_22_LA_CIN,2022021300,CIN,LA,POST,22,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN